#!/usr/bin/env ruby

require "json"

DOTDIR = "dotfiles"

def sh(cmd); system(cmd, exception: true); end

# For the ~/.claude/settings.json merge below.
def deep_merge(base, overlay)
  base.merge(overlay) do |_key, old_val, new_val|
    (old_val.is_a?(Hash) && new_val.is_a?(Hash)) ? deep_merge(old_val, new_val) : new_val
  end
end

Dir.chdir File::expand_path("~")
Dir.foreach(DOTDIR) do |file|
  next unless (file =~ /^\.[a-z]+/ && file != ".git" && file != ".claude")
  if File.directory? "#{DOTDIR}/#{file}"
    dir = file
    unless File.symlink? "#{DOTDIR}/#{dir}"
      sh "mkdir -p #{dir}"
      Dir.foreach("#{DOTDIR}/#{dir}") do |nested_file|
        next if nested_file == "." || nested_file == ".."
        cmd = (nested_file =~ /\.pdf$/) ? "cp" : "ln -Fs"
        sh "#{cmd} ~/#{DOTDIR}/#{dir}/#{nested_file} #{dir}/#{nested_file}"
        puts "#{dir}/#{nested_file} => #{DOTDIR}/#{nested_file}/#{file}"
      end
    end
  else
    sh "ln -Fs #{DOTDIR}/#{file} #{file}"
    puts "#{file} => #{DOTDIR}/#{file}"
  end
end

sh "mkdir -p .config/ghostty"
sh "ln -Fs ~/#{DOTDIR}/ghostty-config .config/ghostty/config"

sh "mkdir -p .config/enchant"
sh "ln -Fs ~/Dropbox/config/enchant/en_US.dic ~/.config/enchant/"

sh "mkdir -p .config/direnv"
sh "ln -Fs ~/#{DOTDIR}/direnv.toml .config/direnv/direnv.toml"

# Claude Code. statusline.py is static, so a symlink is fine. settings.json is
# not: Claude Code rewrites it itself and mixes our preferences in with
# machine-local state (current model, installed plugins, accumulated
# permissions.allow), so we merge in a fragment of just the keys we own.
#
# dotfiles/claude/ has no leading dot so the loop above skips it — .claude is
# excluded there to keep the untracked .claude/settings.local.json out of $HOME.
sh "mkdir -p .claude"
sh "ln -Fs ~/#{DOTDIR}/claude/statusline.py .claude/statusline.py"
puts ".claude/statusline.py => #{DOTDIR}/claude/statusline.py"

sh "mkdir -p .claude/themes"
sh "ln -Fs ~/#{DOTDIR}/claude/themes/loud-user-prompts.json .claude/themes/loud-user-prompts.json"
puts ".claude/themes/loud-user-prompts.json => #{DOTDIR}/claude/themes/loud-user-prompts.json"

settings_path = File.expand_path("~/.claude/settings.json")
fragment      = JSON.parse(File.read("#{DOTDIR}/claude/settings.merge.json"))

# Drop a stale symlink, or File.write would follow it back into the repo.
File.unlink(settings_path) if File.symlink?(settings_path)

live_text = File.exist?(settings_path) ? File.read(settings_path) : nil
live =
  if live_text.nil?
    {}
  else
    begin
      JSON.parse(live_text)
    rescue JSON::ParserError => e
      # Nothing backs settings.json up, so leave what we can't parse alone. Not
      # a `raise`, so the karabiner setup below still runs.
      warn "WARNING: #{settings_path} is not valid JSON (#{e.message.lines.first.strip}); " \
           "skipping the Claude settings merge. Fix it by hand and re-run."
      nil
    end
  end

if live
  merged = JSON.pretty_generate(deep_merge(live, fragment)) + "\n"
  # Claude Code's own format is byte-for-byte what pretty_generate emits, so
  # this makes a repeat run a true no-op rather than racing a live session.
  if merged == live_text
    puts ".claude/settings.json already up to date"
  else
    File.write(settings_path, merged)
    puts ".claude/settings.json <= #{DOTDIR}/claude/settings.merge.json (merged)"
  end
end

sh "cp #{DOTDIR}/harry.gitnote.plist Library/LaunchAgents/harry.gitnote.plist"
sh "launchctl unload Library/LaunchAgents/harry.gitnote.plist || true"
sh "launchctl load Library/LaunchAgents/harry.gitnote.plist"

# karabiner.json is generated by our goku fork (~/workspace/forks/GokuRakuJoudo),
# which we need to use because it understands :conditions on individual to-events.
# To make new computers usable without GraalVM/lein, we version-control the
# generated dotfiles/karabiner.json. On a dev machine the fork is present and we
# rebuild + regenerate; on a fresh machine we just copy the checked-in version
# to the live location.
fork_dir = File.expand_path("~/workspace/forks/GokuRakuJoudo")
forked_goku = "#{fork_dir}/goku"
if File.directory?(fork_dir)
  # Rebuild goku from source so the binary tracks any local fork changes.
  tracked = Dir["#{fork_dir}/src/**/*.clj"] + ["#{fork_dir}/project.clj", "#{fork_dir}/Makefile"]
  stale   = !File.exist?(forked_goku) ||
            tracked.any? { |f| File.exist?(f) && File.mtime(f) > File.mtime(forked_goku) }
  # `make all` is unconditional (cleans first) and takes ~30s, so skip when the
  # binary is newer than every source we'd compile from.
  if stale
    ENV["PATH"]     = "/opt/homebrew/opt/graalvm/bin:#{ENV['PATH']}"
    ENV["CPPFLAGS"] = "-I/opt/homebrew/opt/graalvm/include"
    # Requires `brew install leiningen graalvm`
    sh "cd #{fork_dir} && make all"
  else
    puts "goku binary up-to-date; skipping rebuild"
  end
  # Regenerate dotfiles/karabiner.json. goku reads its input from
  # ~/.config/karabiner/karabiner.json (no env var for the input path), so seed
  # that with the dotfiles copy first; -A then writes the merged result to
  # stdout, which we capture and write back into dotfiles.
  sh "cp #{DOTDIR}/karabiner.json .config/karabiner/"
  edn = File.expand_path("~/#{DOTDIR}/karabiner.edn")
  # NOTE: goku exits 1 after `--dry-run-all` even on success (pre-existing
  # quirk), so don't gate on its exit status — validate the output is parseable
  # JSON instead, which catches actual failures.
  output = `GOKU_EDN_CONFIG_FILE=#{edn} #{forked_goku} -A`
  JSON.parse(output) # raises on garbage / empty output
  File.write("#{DOTDIR}/karabiner.json", output)
else
  warn "NOTE: #{fork_dir} not present — using the checked-in karabiner.json " \
       "without regenerating from karabiner.edn."
end
# Always copy the (possibly just-regenerated) dotfiles karabiner.json to where
# Karabiner-Elements reads it from.
sh "cp #{DOTDIR}/karabiner.json .config/karabiner/"
