#!/usr/bin/env ruby

DOTDIR = "dotfiles"

def sh(cmd); system(cmd, exception: true); end

Dir.chdir File::expand_path("~")
Dir.foreach(DOTDIR) do |file|
  next unless (file =~ /^\.[a-z]+/ && file != ".git" && file != ".claude")
  if File.directory? "#{DOTDIR}/#{file}"
    dir = file
    unless File.symlink? "#{DOTDIR}/#{dir}"
      sh "mkdir -p #{dir}"
      Dir.foreach("#{DOTDIR}/#{dir}") do |nested_file|
        next if nested_file == "." || nested_file == ".."
        cmd = (nested_file =~ /\.pdf$/) ? "cp" : "ln -Fs"
        sh "#{cmd} ~/#{DOTDIR}/#{dir}/#{nested_file} #{dir}/#{nested_file}"
        puts "#{dir}/#{nested_file} => #{DOTDIR}/#{nested_file}/#{file}"
      end
    end
  else
    sh "ln -Fs #{DOTDIR}/#{file} #{file}"
    puts "#{file} => #{DOTDIR}/#{file}"
  end
end

sh "ln -Fs ~/#{DOTDIR}/karabiner.edn .config/karabiner.edn"
# karabiner.json is generated by our goku fork (~/workspace/forks/GokuRakuJoudo),
# which we need to use because it understands :conditions on individual to-events.
# To make new computers usable without GraalVM/lein, we version-control the
# generated dotfiles/karabiner.json. On a dev machine the fork is present and we
# rebuild + regenerate; on a fresh machine we just copy the checked-in version
# to the live location.
fork_dir = File.expand_path("~/workspace/forks/GokuRakuJoudo")
forked_goku = "#{fork_dir}/goku"
if File.directory?(fork_dir)
  # Rebuild goku from source so the binary tracks any local fork changes.
  ENV["PATH"]     = "/opt/homebrew/opt/graalvm/bin:#{ENV['PATH']}"
  ENV["CPPFLAGS"] = "-I/opt/homebrew/opt/graalvm/include"
  sh "cd #{fork_dir} && make all"
  # Regenerate dotfiles/karabiner.json (input AND output redirected to dotfiles).
  edn  = File.expand_path("~/#{DOTDIR}/karabiner.edn")
  json = File.expand_path("~/#{DOTDIR}/karabiner.json")
  sh "GOKU_EDN_CONFIG_FILE=#{edn} GOKU_KARABINER_JSON_FILE=#{json} #{forked_goku}"
else
  warn "NOTE: #{fork_dir} not present — using the checked-in karabiner.json " \
       "without regenerating from karabiner.edn."
end
# Always copy the (possibly just-regenerated) dotfiles karabiner.json to where
# Karabiner-Elements reads it from.
sh "cp #{DOTDIR}/karabiner.json .config/karabiner/"

sh "mkdir -p .config/ghostty"
sh "ln -Fs ~/#{DOTDIR}/ghostty-config .config/ghostty/config"

sh "mkdir -p .config/enchant"
sh "ln -Fs ~/Dropbox/config/enchant/en_US.dic ~/.config/enchant/"

sh "mkdir -p .config/direnv"
sh "ln -Fs ~/#{DOTDIR}/direnv.toml .config/direnv/direnv.toml"

sh "cp #{DOTDIR}/harry.gitnote.plist Library/LaunchAgents/harry.gitnote.plist"
sh "launchctl unload Library/LaunchAgents/harry.gitnote.plist || true"
sh "launchctl load Library/LaunchAgents/harry.gitnote.plist"
